# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171121_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFans',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='粉丝')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='博主')),
            ],
        ),
        migrations.RenameModel(
            old_name='ArticleUp',
            new_name='ArticleUpDown',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='fans',
            field=models.ManyToManyField(related_name='f', through='blog.UserFans', to=settings.AUTH_USER_MODEL, verbose_name='粉丝们'),
        ),
        migrations.AlterUniqueTogether(
            name='userfans',
            unique_together=set([('user', 'follower')]),
        ),
    ]
