# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171122_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article2tag',
            options={'verbose_name_plural': '文章标签对应表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'category', 'verbose_name_plural': '博客个人分类表'},
        ),
        migrations.AlterModelOptions(
            name='userfans',
            options={'verbose_name_plural': '互粉关系表'},
        ),
        migrations.AlterField(
            model_name='article',
            name='site_article_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.SiteArticleCategory', verbose_name='小的二级分类'),
        ),
        migrations.AlterField(
            model_name='sitearticlecategory',
            name='site_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.SiteCategory', verbose_name='所属系统分类'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
    ]
