# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 05:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171124_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentUpDown',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '评论点赞表',
            },
        ),
        migrations.RemoveField(
            model_name='commentup',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentup',
            name='user',
        ),
        migrations.AddField(
            model_name='articleupdown',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='articleupdown',
            unique_together=set([('user', 'article')]),
        ),
        migrations.DeleteModel(
            name='CommentUp',
        ),
        migrations.AlterUniqueTogether(
            name='commentupdown',
            unique_together=set([('user', 'comment')]),
        ),
    ]
