# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171126_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(blank=True, default='/static/theme/headle.css', max_length=32, null=True, verbose_name='博客主题'),
        ),
    ]
