# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171127_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(blank=True, default='static/img/default.png', null=True, upload_to='static/img', verbose_name='头像'),
        ),
    ]
