# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20171127_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(blank=True, default='media/avatar/default.png', null=True, upload_to='media/avatar', verbose_name='头像'),
        ),
    ]
